### PR TITLE
Ep/join table

### PR DESCRIPTION
**Pull request by potash**
temporally correct SpacetimeAggregation `join_table`

### CODE REVIEW

**Comment by potash** [comment]
Hope this isn't too slow on large tables

**Comment by potash** [comment]
the timeout doesn't surprise me. happens to me often with errors in sql execution when called from py.test. annoying.

how could test_helpers.py have a failure? that only touches collate.py which hasnt changed!

**Comment by potash** [comment]
looks passing now? not sure what changed...

**Comment by mbauman** [comment]
Nope, timed out again, but this time with only one failing test:

```
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /home/travis/build/dssg/collate, inifile: 
plugins: cov-2.4.0
collected 19 items 
tests/test_collate.py .........
tests/test_helpers.py ....
tests/test_integration.py .F

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

I restarted the build to try again.

**Comment by thcrock** [comment]
Have you tried the 'testing.Postgresql' module? There are many benefits, but the one that seems relevant here is the fact that there are fewer unreliable moving parts on Travis.

https://github.com/tk0miya/testing.postgresql

Here is its usage in Tyra:
https://github.com/dssg/tyra/blob/master/tests/utils.py

**Pull request merged**
