### PR TITLE
Create table as

### PR DESCRIPTION
**Pull request by potash**
`SpacetimeAggregation` now handles multiple spatial groups through the `group_intervals` argument.

`SpacetimeAggregation.get_creates()` generates one create table per spatial group.

`SpacetimeAggregation.get_drops()` generates one drop table statement per spatial group.

`test_integration.py::test_simple_creates()` tests this

### CODE REVIEW

**Comment by mbauman** [comment]
Note the trailing whitespace.  Don't bother fixing the longish lines; we can just change flake's config for that.

**Comment by mbauman** [comment]
(merged with master to fix the line length flake error)

**Comment by mbauman** [comment]
Are you happy with the state of this branch?  Let me know and I'll work on reviewing it.

**Comment by potash** [comment]
Yes, please review





---- On Wed, 16 Nov 2016 15:52:37 -0600Matt Bauman &lt;notifications@github.com&gt; wrote ----




Are you happy with the state of this branch? Let me know and I'll work on reviewing it.

**Comment by potash** [comment]
Added support for agg functions of multiple arguments like `corr`

**Comment by mbauman** [comment]
Hm, I may have merged this prematurely.

```py
In [34]: pd.read_sql("""SELECT "Inspection Date", "Results" from food_inspections where "License #" = 80273 and "Results" = 'Fail'""", engine)
Out[34]:
  Inspection Date Results
0      2016-09-30    Fail
1      2015-04-20    Fail
2      2014-09-10    Fail

In [35]: pd.read_sql('SELECT * FROM "food_inspections_License #" WHERE "License #" = 80273', engine)
Out[35]:
   License #        date  \
0    80273.0  2016-08-31
1    80273.0  2015-08-31

   food_inspections_License #_1 year_ Results = 'Fail'_count  \
0                                                          1
1                                                          5

   food_inspections_License #_2 years_ Results = 'Fail'_count  \
0                                                           6
1                                                           6

   food_inspections_License #_all_ Results = 'Fail'_count
0                                                       9
1                                                       8
```

**Pull request merged**
