### PR TITLE
Add multiple comparison Aggregate subclasses

### LINKED ISSUE #35: add parameter to do exact or substring match (like %string%) when doing aggregations

### PR DESCRIPTION
**Pull request by mbauman**
This drastically can simplify the writing of categorical comparisons:

        """
        Args:
            col: the column name (or equivalent SQL expression)
            op: the SQL operation (e.g., '=' or '~' or 'LIKE')
            choices: A list or dictionary of values. When a dictionary is
                passed, the keys are a short name for the value.
            function: (from Aggregate)
            order: (from Aggregate)
            include_null: Add an extra `{col} is NULL` if True (default True)
            maxlen: The maximum length of aggregate quantity names, if specified.
                Names longer than this will be truncated.
            op_in_name: Include the operator in aggregate names (default False)

        A simple helper method to easily create many comparison columns from
        one source column by comparing it against many values. It effectively
        creates many quantities of the form "({col} {op} {elt})::INT" for elt
        in choices. It automatically quotes strings appropriately and leaves
        numbers unquoted. The type of the comparison is converted to an
        integer so it can easily be used with 'sum' (for total count) and
        'avg' (for relative fraction) aggregate functions.

        By default, the aggregates are named "{col}_{op}_{elt}", but the
        operator may be ommitted if `op_in_name=False`. This name can become
        long and exceed the maximum column name length. If ``maxlen`` is
        specified then any aggregate name longer than ``maxlen`` gets
        truncated with a number appended to ensure that they remain unique and
        identifiable (but note that sequntial ordering is not preserved).
        """

Use it like:

```py
from collate import collate

collate.Categorical('food', ['hamburger','hotdog','sock'], ['sum','avg'])
collate.Compare('food', 'LIKE', ['ham%', '%otdo%', '%ock'],['sum'])
```

Fixes #35.

### CODE REVIEW

**Comment by potash** [comment]
Nice, this is almost exactly what I had in mind.

I would prefer the following:
1) make op '=' by default, this will be the most used.
2) default to `maxlen=None`, i.e. no truncation. 
3) Make including the op in the quantity name optional, maybe default to not including it, at least when op is `'='`.
4) Support for categoricals that are not strings, like numeric codes (detect whether the value is string-like and only quote it then).

In fact with all this is it really appropriate to call this `categorical`? To me, categorical is when there is equality. Maybe the more general thing should be called `conditional` or `boolean`. For example I might use this for a totally non-cateogircal thing like "sum( (waste_generated > 100)::int)".

There are other things like this to write for example binning numeric values: `bin("waste_generated", 0, 100,10)` would map to quantites `{"waste_generated_0_10": waste_generated >= 0 and waste_generated < 10)::int", "waste_generated_10_20": "(waste_generated >= 10 and waste_generated < 20)::int",...}`

Also I was going to make it a class (extending `Aggregate`) instead of a helper for building quantity dict, i.e.:
```
Categorical('food', '=', ['hamburger','hotdog','sock'], ['sum','avg'])
```
I guess they are equivalent. The one place where I see the class being an advantage is for example if/when we add a `help` or `explanation` arg to Aggregate for the metafeature table, the subclass approach is easier for building those strings and passing them to a super constructor.

What do you think?

**Comment by mbauman** [comment]
Yes, I almost entirely agree.  The only reason I didn't make `op='='` by default is because I liked the order of `categorical('col', '=', ['a','b','c'])`.  With regards to its name, maybe something like `MultiComparison`?

I'll make it an extremely simple superclass for now, so that way we can keep the API and add more features to it as we go.

**Comment by mbauman** [comment]
Ok, updated!  With regards to your suggestions:


> 1\. make op '=' by default, this will be the most used.

This has not changed, you must always specify `op`, even in the common case `op='='`.

> 2\. default to maxlen=None, i.e. no truncation.

Done!

> 3\. Make including the op in the quantity name optional, maybe default to not including it, at least when op is '='.

op is not included in the quantity name when it is `'='`.

> 4\. Support for categoricals that are not strings, like numeric codes (detect whether the value is string-like and only quote it then).

Done!  I've opted to test for `isinstance(x, Number)`, and only when that is true is it inserted without quotes.

> In fact with all this is it really appropriate to call this `categorical`

Renamed to `MultiCompare`.  Still open to suggestions for something better, but I definitely agree that `categorical` isn't that great.

And, finally, I made this a very simple wrapper superclass.  No extra functionality is defined, but this way the API doesn't need to change if we decide to implement special cases for a set of multiple comparisons.

**Comment by thcrock** [comment]
What do you think about using kwargs here? It would make the '=' default a non-issue, and the call signature is long enough that I think it would be hard to remember the order of the arguments unless  copy+pasting from an existing call.

**Comment by mbauman** [comment]
Sure, that makes sense.  Any thoughts on the name of the class?

**Comment by potash** [comment]
1. I'd just call it `Compare` because, unless I'm missing something, the `Multi` is in the sense of broadcasting and that happens with pretty much everything in collate so there's no reason to specify it here.

2. Re: kwargs and default `op="="`, what about a subclass called `Categorical` that calls `Compare.__init__(...,op='=')`?

**Comment by potash** [comment]
Also if we go the `Categorical` route, I suggest the `Compare` constructor take an arg for explicitly allowing the `op` to be included in the quantity names (default `True`?) and then `Categorical` can set it to `False`.

**Comment by mbauman** [comment]
OK, @potash, I think this is ready to go.

**Comment by potash** [comment]
Looks good. Do you have strong feelings about the  `include_null=True` default? To me it seems unintuitive for
```
Compare('col', '=', [1,2,3])
```
to include nulls because "null" doesn't appear in the call. Thouhts?

**Comment by mbauman** [comment]
In nearly all the code I've been translating, we've had a NULL column for categorical-like features, so I thought that the default would mirror the most common usage.

That said, I'm reconsidering it, as I think it really belongs as an imputation sort of post-processing step.

**Comment by potash** [comment]
Hmm even if include_null is the most commonly used, it seems worth making it explicit.
Yeah, I almost want to make the syntax
```
Compare("col","=",[1,2,3,None])
```
And translate `None` to `is null`. But that seems hacky?

**Comment by mbauman** [comment]
I like that initially, but it gets weird with other operators: `Compare('col', '!=', [1,2,None])`. We could do it in `Categorical`, though.

**Comment by potash** [comment]
Good point. `include_null` is itself a little funny with other operators. I propose

1) make the default `Compare(...,include_null=False)`

Then we've shifted the question to `Categorical` where we can either
a) more sanely do some `None` magic
b) make `include_null=True` the default, though maybe its confusing that the default varies in places
c) leave the default as `False`

**Comment by mbauman** [comment]
Agreed. I'm leaning towards option 1a.

**Comment by mbauman** [comment]
Ok, updated once again.  I think this is ready.

**Comment by potash** [comment]
Looks good except I would not ignore the alias for `None` if they provided one. For example maybe a `null` treatment status code means "incomplete" and they pass `{"incomplete": None,...}`

**Comment by mbauman** [comment]
Fair enough.  I think the simplest way to do that requires leaning on truthy strings, but it seems sensible.

**Pull request merged**
